CREATE TABLE `QUESTION_TABLE` (
	`QUESTION_ID`	VARCHAR(50)	NOT NULL,
	`QUESTION`	VARCHAR(225)	NULL
);

CREATE TABLE `SCORE_TABLE` (
	`SCORE_ID`	VARCHAR(50)	NOT NULL,
	`SCORE`	DECIMAL(2,0)	NULL
);

CREATE TABLE `CHOICE_ANSWER_TABLE` (
	`CHOICE_ID`	VARCHAR(50)	NOT NULL,
	`QUESTION_ID`	VARCHAR(50)	NOT NULL,
	`SCORE_ID`	VARCHAR(50)	NOT NULL,
	`CHOICE`	VARCHAR(225)	NULL,
	`CHOICE_NUMBER`	VARCHAR(225)	NULL
);

CREATE TABLE `USER_INFO_TABLE` (
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`USER_NAME`	VARCHAR(225)	NULL
);

CREATE TABLE `USER_ANSWER_TABLE` (
	`USER_ANSWER_ID`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`CHOICE_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `QUESTION_TABLE` ADD CONSTRAINT `PK_QUESTION_TABLE` PRIMARY KEY (
	`QUESTION_ID`
);

ALTER TABLE `SCORE_TABLE` ADD CONSTRAINT `PK_SCORE_TABLE` PRIMARY KEY (
	`SCORE_ID`
);

ALTER TABLE `CHOICE_ANSWER_TABLE` ADD CONSTRAINT `PK_CHOICE_ANSWER_TABLE` PRIMARY KEY (
	`CHOICE_ID`,
	`QUESTION_ID`,
	`SCORE_ID`
);

ALTER TABLE `USER_INFO_TABLE` ADD CONSTRAINT `PK_USER_INFO_TABLE` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `USER_ANSWER_TABLE` ADD CONSTRAINT `PK_USER_ANSWER_TABLE` PRIMARY KEY (
	`USER_ANSWER_ID`,
	`USER_ID`,
	`CHOICE_ID`
);

ALTER TABLE `CHOICE_ANSWER_TABLE` ADD CONSTRAINT `FK_QUESTION_TABLE_TO_CHOICE_ANSWER_TABLE_1` FOREIGN KEY (
	`QUESTION_ID`
)
REFERENCES `QUESTION_TABLE` (
	`QUESTION_ID`
);

ALTER TABLE `CHOICE_ANSWER_TABLE` ADD CONSTRAINT `FK_SCORE_TABLE_TO_CHOICE_ANSWER_TABLE_1` FOREIGN KEY (
	`SCORE_ID`
)
REFERENCES `SCORE_TABLE` (
	`SCORE_ID`
);

ALTER TABLE `USER_ANSWER_TABLE` ADD CONSTRAINT `FK_USER_INFO_TABLE_TO_USER_ANSWER_TABLE_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER_INFO_TABLE` (
	`USER_ID`
);

ALTER TABLE `USER_ANSWER_TABLE` ADD CONSTRAINT `FK_CHOICE_ANSWER_TABLE_TO_USER_ANSWER_TABLE_1` FOREIGN KEY (
	`CHOICE_ID`
)
REFERENCES `CHOICE_ANSWER_TABLE` (
	`CHOICE_ID`
);

